# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purposes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purposes',
            new_name='Purpose',
        ),
    ]
