# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 16:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('purposes', '0003_purpose_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='purpose',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 23, 16, 0, 52, 161376, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purpose',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 4, 23, 16, 1, 19, 977599, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
